### ISSUE TITLE
[$40] - Bug when trying to reset password using Safari

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#908] opened 2016-12-15 17:48 UTC
Case : https://topcoder.zendesk.com/agent/tickets/4733 

When the member tried to open "password reset" URL using Safari, he redirected to the main login page. however when use same URL in Chrome it worked fine.

**Comment by birdofpreyru** [comment] 2017-01-23 23:25
I can't test this issue, as I don't have Mac. Thus, in this ticket you are supposed to test whether this issue is indeed present on Safari:
1. If the issue is valid, you should fix it and provide a short video demonstrating that your fix works.
2. If the issue is not valid, just provide a short video confirming it. The payment will be just $10 in this case.

**Comment by dmitrysobolev** [comment] 2017-01-24 15:26
Please assign me to this issue, I have no permissions to do that

**Comment by birdofpreyru** [comment] 2017-01-24 15:28
@dmitrysobolev It is yours :)

**Comment by birdofpreyru** [comment] 2017-01-26 08:32
@dmitrysobolev Any update on this?

**Comment by dmitrysobolev** [comment] 2017-01-27 06:12
The bug could be easily reproduced in Safari https://accounts.topcoder.com/member/forgot-password, and it seems that the issue is in https://github.com/appirio-tech/accounts-app. At 'dev' environment everything works just fine in Chrome and Safari (http://accounts.topcoder-dev.com/member/forgot-password), and this is partly the reason why it is not easy to detect the bug.

**Comment by birdofpreyru** [comment] 2017-01-27 10:12
@dmitrysobolev Do you keep on working to fix it?

**Comment by dmitrysobolev** [comment] 2017-01-27 15:26
Sorry, but i think I stop now. It could require much effort from my side because I am not familiar with the application in such a deep level.

**Comment by birdofpreyru** [comment] 2017-01-27 18:49
@dmitrysobolev Are you interested to resolve this issue for a higher payment?

**Comment by dmitrysobolev** [comment] 2017-01-27 23:25
I will try to resolve it on this weekend

**Comment by birdofpreyru** [comment] 2017-01-30 13:17
@dmitrysobolev Any progress with this one? If not, I'd like to open this issue for pickup by other members.

**Comment by dmitrysobolev** [comment] 2017-01-31 03:21
Still no progress, sorry. Please open it for pickup.

**Comment by rainerlopez** [comment] 2017-02-06 00:08
I'll set everything up here and see if I can help on this one.

**Comment by ThomasKranitsas** [comment] 2017-02-06 16:33
@rainerlopez Will you work on this one or can I fix it?

**Comment by rainerlopez** [comment] 2017-02-06 16:36
Go for it @ThomasKranitsas ! Tkx for asking. I'm still setting the enviroments up here.

**Comment by birdofpreyru** [comment] 2017-02-15 13:01
@ThomasKranitsas Any progress with this one? If you not, and you are not interested in it, we can open it to public for the new BugBash which is coming shortly :)

**Comment by ThomasKranitsas** [comment] 2017-02-15 13:02
Hey @birdofpreyru! I'm working on this right now.. I found the source of the issue and I'll submit a PR in the next hour

**Comment by ThomasKranitsas** [comment] 2017-02-15 13:26
To test it locally you can modify the `node_modules/appirio-tech-webpack-config/constants.coffee` to change `API_URL` & `API_URL_V2` to the production instead of -dev

**Comment by birdofpreyru** [comment] 2017-02-15 13:31
@ThomasKranitsas I'm not sure I can, as I don't have any Mac around, and I could not reproduce the problem with other browser/OS. Can you make a brief video to show the original problem, and that it is fixed with the new code?

**Comment by ThomasKranitsas** [comment] 2017-02-15 13:33
Sure! Give me few minutes..

**Comment by ThomasKranitsas** [comment] 2017-02-15 13:41
Here's the video: http://take.ms/SoMQt
I sent a reset link recently thus I couldn't send another one... But you can see that when I open the link in Safari it doesn't redirect anywhere but instead it shows the Create new pass textbox as expected.

**Closed** 2017-02-21 23:21 UTC
Labels: BugBash - ACCEPTED
