### ISSUE TITLE
$25 - My Challenges--All blue line should be of same size on IE 11

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/topcoder-app#675] opened 2016-01-19 23:36 UTC
JIRA: https://appirio.atlassian.net/browse/SUP-2699

** Steps to reproduce** 
1. Login as iamtong on IE 11.
2. Open my challenges.
3. Verify the blue line on card.
![capture-for-jira-screenshot-20151118-232958-325](https://cloud.githubusercontent.com/assets/1987710/12435409/44d6f95a-bec2-11e5-9a26-ea1b4e250707.png)

**Comment by shubhendusaurabh** [comment] 2016-02-01 17:42
how do i login as iamtong or any member with past challenges?

**Comment by nlitwin** [comment] 2016-02-01 22:02
Hi @shubhendusaurabh, the password for any member in dev is appirio123

**Comment by meirka5** [comment] 2016-02-03 20:49
![capture___5](https://cloud.githubusercontent.com/assets/4015911/12796617/5ac84c02-cac8-11e5-899e-1da3d5906e36.GIF)
Still is 100 pixels, which is longer than the other blue lines.

**Comment by nlitwin** [comment] 2016-02-08 19:24
We do want it to be as tall as the header, since the header is not always the same height. The blue line should just not overflow past the header. I'm going to close this issue, since it was fixed in a previous change, and I can no longer reproduce the original issue. Sorry for any confusion!

**Closed by nlitwin** 2016-02-08 19:24 UTC
Labels: COMMUNITY BUGFIX, Small

**Comment by vikasrohit** [comment] 2016-02-09 06:03
Thanks @nlitwin  for the confirmation.
