### ISSUE TITLE
Data Science RSS Feed broken

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/topcoder-app#951] opened 2017-01-25 14:55 UTC
Refer to http://apps.topcoder.com/forums/?module=Message&messageID=2179445

This feed is currently generated by a small heroku app.  We could fix that app, or take a new approach to generating these feeds...maybe from the v3 challenges API...

**Comment by ajefts** [comment] 2017-01-25 14:56
@birdofpreyru Can we add this one to the list?

**Comment by birdofpreyru** [comment] 2017-01-25 14:58
@ajefts Sure, just refer, please, to the repos which contain related code for the backend API and for that Heroku App you mention.

Also, can you please check your Slack? I've send you a message there about login problems I suddenly got with `topcoder-dev.com`.

**Comment by ajefts** [comment] 2017-01-25 15:14
@birdofpreyru Here is the repo for it.  I'll add you to the heroku app too.

As I mentioned...I'm not tied to this heroku service as the way to do this.  It was kind of a quick hack years ago to throw a feed together.

**Comment by birdofpreyru** [comment] 2017-01-25 20:34
@ajefts OK. I'll just fix it myself. The problem is that the deployed instance of this Heroku App, when calls TC API to get the listing of data challenges, passes in the request `pageSize=2147483647`, and the API rejects `pageSize` larger than 100. When I deployed this Heroku App locally, it uses `pageSize=51` and the data science RSS works fine.

**Comment by birdofpreyru** [comment] 2017-01-25 21:38
@ajefts Fixed by deploying the latest version of the App from the repo to Heroku. It looks like everything is working fine now, but I have not look too much into details, so if somebody report any problems with RSS feeds, we should not be very surprised.

**Closed** 2017-01-25 21:39 UTC

**Comment by ajefts** [comment] 2017-01-25 21:59
Awesome @birdofpreyru.  what would you have priced this at?

**Comment by birdofpreyru** [comment] 2017-01-25 22:07
@ajefts This wasn't that difficult, to ask for a separate payment for it :) Though, if at any time you feel like adding more $$$ for my co-piloting work, I never reject money :-D
